### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by TowerScience** [Arephese/intro-data-capstone-biodiversity#1]
Scores: 
Code - 4, All the graphs are correct and your numbers and p-values are accurate.
Hypothesis - 4, Clearly stated the hypothesis that was being tested
Interpretations - 4, Correctly advised conservation efforts to focus on mammals and birds
Presentation - 4, Clean presentation, amusing graphics, presents information easily.

Overall 16/16 - Exceeds expectations.

**Comment by Arephese** [comment]
Thanks!
